---
# yamllint disable rule:line-length
- name: Trackpad - map bottom right corner to right-click
  shell: "defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2"

- name: Trackpad - map bottom right corner to right-click
  shell: "defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true"

- name: Trackpad - map bottom right corner to right-click
  shell: "defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1"

- name: Trackpad - map bottom right corner to right-click
  shell: "defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true"

# (e.g. enable Tab in modal dialogs - 0 = text boxes and lists, 2/3 = all controls)
- name: Enable full keyboard access for all controls
  shell: "defaults write NSGlobalDomain AppleKeyboardUIMode -int 0"

- name: Use scroll gesture with the Ctrl (^) modifier key to zoom
  shell: "defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true"

- name: dUse scroll gesture with the Ctrl (^) modifier key to zoom
  shell: "defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144"

- name: Follow the keyboard focus while zoomed in
  shell: "defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true"

...
