---
# yamllint disable rule:line-length

- name: Set Safari’s home page
  shell: "defaults write com.apple.Safari HomePage -string '{{ safari_homepage }}'"

- name: Prevent Safari from opening ‘safe’ files automatically after downloading
  shell: "defaults write com.apple.Safari AutoOpenSafeDownloads -bool false"

- name: Enable the Develop menu and the Web Inspector in Safari
  shell: "defaults write com.apple.Safari IncludeDevelopMenu -bool true"

- name: Enable the Develop menu and the Web Inspector in Safari
  shell: "defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true"

- name: Enable the Develop menu and the Web Inspector in Safari
  shell: "defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true"

- name: Add a context menu item for showing the Web Inspector in web views
  shell: "defaults write NSGlobalDomain WebKitDeveloperExtras -bool true"

...
