---
# yamllint disable rule:line-length

- name: Save screenshots to the desktop
  shell: "defaults write com.apple.screencapture location -string '${HOME}/Desktop'"

- name: Save screenshots in PNG format (other options BMP, GIF, JPG, PDF, TIFF)
  shell: 'defaults write com.apple.screencapture type -string "png"'

- name: Disable shadow in screenshots
  shell: "defaults write com.apple.screencapture disable-shadow -bool true"
  when: disable_screenshot_shadow

...
